### ISSUE TITLE
Thin + Capistrano: Gemfile not found (Bundler::GemfileNotFound)

### ISSUE THREAD

**Issue by deepsystm** [freego/capistrano-thin#4]
Hi freego!
Anybody know's how to solve thin crashes after restart, in use with capistrano?

My thin running as websocket server only, but sometimes in log I see this:
```
oken":null}]])
oken":null}]])
Restarting ...
Waiting for 4 connection(s) to finish, can take up to 30 sec, CTRL+C to stop now
/var/www/rails/shared/bundle/ruby/2.1.0/bin/thin start --chdir="/var/www/rails/current" --environment="production" --address="
localhost" --port=6123 --timeout=30 --log="/var/www/rails/shared/log/websocket_rails_server.log" --pid="/var/www/rails/shared/
tmp/pids/websocket_rails.pid" --max-conns=1024 --max-persistent-conns=1024 --wait=30 --threadpool-size=20 --trace --daemonize --ta
g="websocket_rails" --rackup="/var/www/rails/current/config.ru"
/home/ds/.rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.4/lib/bundler/definition.rb:22:in `build': /var/www/rails/releases/2015041
9101856/Gemfile not found (Bundler::GemfileNotFound)

        from /home/ds/.rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.4/lib/bundler.rb:154:in `definition'

        from /home/ds/.rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.4/lib/bundler.rb:117:in `setup'

        from /home/ds/.rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.4/lib/bundler/setup.rb:17:in `<top (required)>'

        from /home/ds/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'

        from /home/ds/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

Crash happens because linked dir does not exist after several deploys
but, what can I do to solve this?

Thanks!

**Comment by alepore** [comment]
Hi,
are you using this gem?
That seems the kind of problems this gems is trying to solve :)

**Comment by deepsystm** [comment]
it work fine when i'm deploy project

but it crashes after several hours, days when thin restarts itself

**Comment by alepore** [comment]
i'm sorry, is this actually related to this gem?
